### ISSUE TITLE
Stakeholder analysis

### ISSUE THREAD

**Issue by KarmaKamikaze** [KarmaKamikaze/FCDS#12]
Interessentanalyse på Systime:
https://projektarbejdet.systime.dk/?id=185

Interessantanalyse: Hvem er interesseret, hvem er det vi henvnder os til og arbejder med,

Noget viden generelt omkring kunder & ansatte – hvad kan vores ansatte hvordan/ hvad er deres kapaciteter og hvordan påvirker det udformingen af produtket. - hvad skal de have af information og hvordan skal det præsenteres for at de kan arbejde effeciently.

Kunder – what do they want og hvordan påvirker det udformningen af proudktet.

New ændringer der skal laves:
Forkort det
Ryk det længere op (under hv -mindmap?)

Hvem er klientetn I modsatte side – hvilke forretninger anvender appen/platformen/servicen - og hvordan anvender de den.

**Comment by SimonPRasmussen** [comment]
Sætningne "The aim of the project" indegå faretruende mange gange, og jeg frygter den ikke giver consistent svar ift. at aim conflicter til tider bl.a. ift CS vs research aspektet

   -come see me in my office for further inquiries.
          Simon

**Comment by SimonPRasmussen** [comment]
Notes for reviewers:

Det skal reviewes in conjunction med 2.1 'Food delivery' (dvs. spring Hv-mindmap-afsnitter over) - Jeg har inkorporeret de ting fra 2.1 Food delivery der basically var stakeholder analysis ind i stakeholder analysen (det er de dele commented ud af 2.1 linje 38-46). Det betyder at stakeholder analysen er blevet længere, men krydsreferencerne er blevet substantially mindre og det er mindre selv-itererende - så rapporten som helhed er blevet kortere, og der er lidt mere kongruens og consistency i stakeholderanalysen, og afsnittene fra 2.1 har lidt mere konklusion og perspektiv ift. resten af rapporten.
I stakeholder analysen er det kun stakeholdersne 'couriers' og 'FD service companies' under kategorien 'Manage closely' der er ændret, ('economy' fra 'monitor' kategorien er uændret for nu).
Jeg må indrømme, atjeg har stirret mig lidt blind på det, så er der dele der virker lidt ude at takt fra andre eller usammenhængende, så sæt gerne lige en note, så kigger jeg lige på det - i behøver ikke bruge tid på at give feedback på de dele.
Alt feedback er velkommen, men husk på at hvis det er negativt, så græder jeg mig selv i søvn i nat
