### ISSUE TITLE
Tests chapter

### ISSUE THREAD

**Issue by Sarmisuper** [KarmaKamikaze/FCDS#158]

**Comment by KarmaKamikaze** [comment]
Tilføj en henvisning til appendix, når du snakker om testOrderAssignment eller runAllTests, da disse ikke er til at finde i den snippet der er i test afsnittet. 

Derudover må du gerne tilføje en redegørelse over, hvorfor vi ikke har lavet flere tests end dem vi har nu. Brug gerne nogle af test-termerne, så som unit testing, integration testing og end-to-end. Jeg synes også vi skal tilføje at en ukendt årsag gjorde at et konventionelt test framework ikke virkede til at teste prorammet, da det meste foregår på client side. Selvom vi prøvede at gøre brug af et headless browser framework, så virkede vores cytoscape importering ikke i test suiten.
